version: 0.2    

env:
    git-credential-helper: yes

phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel LTS 
        
  pre_build:
    commands:
      - git submodule update --init --recursive
      
  build:
    commands:
      - dotnet restore src/NopCommerce.sln
      - dotnet build src/NopCommerce.sln

artifacts:
  files:
    - 'src/Presentation/Nop.Web/Plugins/Payments.SimplePay/**/*'